export const prerender = false;
import type { APIRoute } from 'astro';
import { createHmac } from 'node:crypto';
import { getSupabaseServiceClient } from '@lib/services/providers/supabase/SupabaseDB';
import { resolveFromRequest } from '@lib/permissions';
import { normalizeError } from '@lib/middleware/errorNormalizer';
import { writeAuditLog, extractClientIP } from '@lib/middleware/auditLogger';
import { UUID_RE } from '@lib/constants';

const SOCIETY_ID      = import.meta.env.PUBLIC_SOCIETY_ID ?? '00000000-0000-0000-0000-000000000001';
const RAZORPAY_SECRET = import.meta.env.RAZORPAY_KEY_SECRET ?? '';

// POST /api/v1/finance/payments/razorpay-verify
// Verifies a Razorpay payment signature, then records the payment against the dues record.
// Body: { razorpay_order_id, razorpay_payment_id, razorpay_signature, dues_id }
export const POST: APIRoute = async ({ request }) => {
  try {
    const user = await resolveFromRequest(request, SOCIETY_ID);
    if (!user) return Response.json({ error: 'UNAUTHORIZED' }, { status: 401 });

    if (!RAZORPAY_SECRET) return Response.json({ error: 'NOT_CONFIGURED' }, { status: 503 });

    const body = await request.json() as {
      razorpay_order_id?: string;
      razorpay_payment_id?: string;
      razorpay_signature?: string;
      dues_id?: string;
    };

    const { razorpay_order_id, razorpay_payment_id, razorpay_signature, dues_id } = body;

    if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
      return Response.json({ error: 'VALIDATION', message: 'razorpay_order_id, razorpay_payment_id, razorpay_signature required' }, { status: 400 });
    }
    if (!dues_id || !UUID_RE.test(dues_id)) {
      return Response.json({ error: 'VALIDATION', message: 'valid dues_id required' }, { status: 400 });
    }

    // Verify HMAC-SHA256 signature: HMAC(order_id + '|' + payment_id, secret)
    const expectedSig = createHmac('sha256', RAZORPAY_SECRET)
      .update(`${razorpay_order_id}|${razorpay_payment_id}`)
      .digest('hex');

    if (expectedSig !== razorpay_signature) {
      return Response.json({ error: 'SIGNATURE_INVALID', message: 'Payment signature verification failed' }, { status: 400 });
    }

    const sb = getSupabaseServiceClient();

    // Fetch the order record
    const { data: order, error: orderErr } = await sb
      .from('online_payment_orders')
      .select('id, dues_id, amount, status, user_id')
      .eq('razorpay_order_id', razorpay_order_id)
      .eq('society_id', SOCIETY_ID)
      .single();

    if (orderErr || !order) return Response.json({ error: 'NOT_FOUND', message: 'Order not found' }, { status: 404 });
    if (order.status === 'paid') return Response.json({ error: 'CONFLICT', message: 'Payment already recorded' }, { status: 409 });
    if (order.dues_id !== dues_id) return Response.json({ error: 'VALIDATION', message: 'dues_id mismatch' }, { status: 400 });

    // Members can only pay their own dues
    const isExec = user.isAdmin ||
      ['executive', 'secretary', 'president'].includes(user.portalRole ?? '') ||
      ['executive', 'admin'].includes(user.role ?? '');
    if (!isExec && order.user_id !== user.id) {
      return Response.json({ error: 'FORBIDDEN' }, { status: 403 });
    }

    // Fetch dues record
    const { data: due } = await sb
      .from('maintenance_dues')
      .select('id, user_id, total_amount, amount_paid, status')
      .eq('id', dues_id)
      .eq('society_id', SOCIETY_ID)
      .single();

    if (!due) return Response.json({ error: 'NOT_FOUND', message: 'Dues record not found' }, { status: 404 });
    if (due.status === 'paid' || due.status === 'waived') {
      return Response.json({ error: 'CONFLICT', message: `Dues already ${due.status}` }, { status: 409 });
    }

    const alreadyPaid  = Number(due.amount_paid ?? 0);
    const totalDue     = Number(due.total_amount);
    const orderAmount  = Number(order.amount);
    const outstanding  = Math.max(0, totalDue - alreadyPaid);
    const paidNow      = Math.min(orderAmount, outstanding + 0.005);
    const excess       = Math.max(0, orderAmount - outstanding);
    const newAmountPaid = alreadyPaid + paidNow;
    const newStatus    = newAmountPaid >= totalDue - 0.005 ? 'paid' : 'partially_paid';

    // 1. Record payment (receipt_number auto-generated by trigger)
    const { data: payment, error: payErr } = await sb
      .from('payments')
      .insert({
        society_id:      SOCIETY_ID,
        dues_id,
        user_id:         due.user_id,
        amount:          orderAmount,
        payment_mode:    'online',
        transaction_ref: razorpay_payment_id,
        recorded_by:     user.id,
        paid_at:         new Date().toISOString(),
      })
      .select()
      .single();

    if (payErr) throw Object.assign(new Error(payErr.message), { status: 500 });

    // 2. Payment allocation
    await sb.from('payment_allocations').insert({
      payment_id:       payment.id,
      dues_id,
      amount_allocated: paidNow,
    });

    // 3. Update dues status
    const duesUpdate: Record<string, unknown> = { amount_paid: newAmountPaid, status: newStatus };
    if (newStatus === 'paid') duesUpdate.paid_at = payment.paid_at;
    await sb.from('maintenance_dues').update(duesUpdate).eq('id', dues_id);

    // 4. Create member credit if excess
    let credit = null;
    if (excess > 0.005) {
      const { data: creditRow } = await sb.from('member_credits').insert({
        society_id:     SOCIETY_ID,
        user_id:        due.user_id,
        amount:         Math.round(excess * 100) / 100,
        source_payment: payment.id,
        notes:          `Advance credit from Razorpay payment ${payment.receipt_number}`,
      }).select().single();
      credit = creditRow;
    }

    // 5. Mark order as paid
    await sb.from('online_payment_orders').update({
      status:               'paid',
      razorpay_payment_id,
      razorpay_signature,
      payment_id:           payment.id,
    }).eq('id', order.id);

    await writeAuditLog({
      societyId: SOCIETY_ID,
      userId:    user.id,
      action:    'PAYMENT',
      resourceType: 'payments',
      resourceId:   payment.id,
      newValues: {
        amount: orderAmount, payment_mode: 'online',
        razorpay_payment_id, dues_id, new_status: newStatus,
      },
      ip: extractClientIP(request),
    });

    return Response.json({
      payment,
      dues_status:    newStatus,
      amount_paid:    newAmountPaid,
      outstanding:    Math.max(0, totalDue - newAmountPaid),
      credit_created: credit ? { id: (credit as any).id, amount: (credit as any).amount } : null,
    }, { status: 201 });
  } catch (err) {
    return normalizeError(err, request.url);
  }
};
