export const prerender = false;
import type { APIRoute } from 'astro';
import { getSupabaseServiceClient } from '@lib/services/providers/supabase/SupabaseDB';
import { resolveFromRequest, requireAdmin } from '@lib/permissions';
import { loadRules, r, RULE } from '@lib/rules';
import { normalizeError } from '@lib/middleware/errorNormalizer';

const SOCIETY_ID = import.meta.env.PUBLIC_SOCIETY_ID ?? '00000000-0000-0000-0000-000000000001';

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

const VALID_ROLES = ['member', 'executive', 'secretary', 'president'] as const;

// POST — invite a new member
// Auth: admin required
// Body: { email, flat_number, intended_role, committee_title? }
// - Validates email format
// - Checks INVITE_EMAIL_DOMAIN_ALLOWLIST rule
// - INSERTs into member_invites; token generated by DB default
// - Returns { id, email, token_expires_at } — raw token is NOT returned
export const POST: APIRoute = async ({ request }) => {
  try {
    const user = await resolveFromRequest(request, SOCIETY_ID);
    if (!user) {
      return Response.json(
        { error: 'UNAUTHORIZED', message: 'Authentication required' },
        { status: 401 },
      );
    }

    requireAdmin(user);

    const body = await request.json() as {
      email?: string;
      flat_number?: string;
      intended_role?: string;
      committee_title?: string;
    };

    // Validate required fields
    if (!body.email || typeof body.email !== 'string') {
      return Response.json(
        { error: 'VALIDATION_ERROR', message: 'email is required' },
        { status: 400 },
      );
    }

    const email = body.email.trim().toLowerCase();

    if (!EMAIL_RE.test(email)) {
      return Response.json(
        { error: 'VALIDATION_ERROR', message: 'email is not a valid email address' },
        { status: 400 },
      );
    }

    if (!body.flat_number || typeof body.flat_number !== 'string') {
      return Response.json(
        { error: 'VALIDATION_ERROR', message: 'flat_number is required' },
        { status: 400 },
      );
    }

    const intendedRole = body.intended_role ?? 'member';
    if (!VALID_ROLES.includes(intendedRole as typeof VALID_ROLES[number])) {
      return Response.json(
        { error: 'VALIDATION_ERROR', message: `intended_role must be one of: ${VALID_ROLES.join(', ')}` },
        { status: 400 },
      );
    }

    // Load rules for allowlist check and expiry config
    const rules = await loadRules(SOCIETY_ID);

    // Check domain allowlist — if non-empty, email domain must be in list
    const allowlist = r<string[]>(rules, RULE.INVITE_EMAIL_DOMAIN_ALLOWLIST, []);
    if (Array.isArray(allowlist) && allowlist.length > 0) {
      const domain = email.split('@')[1];
      if (!allowlist.includes(domain)) {
        return Response.json(
          {
            error: 'VALIDATION_ERROR',
            message: `Email domain '${domain}' is not in the allowed list. Permitted domains: ${allowlist.join(', ')}`,
          },
          { status: 400 },
        );
      }
    }

    const expiryDays = r<number>(rules, RULE.INVITE_EXPIRY_DAYS, 7);

    const sb = getSupabaseServiceClient();

    // Check if there is already a pending (non-expired, non-accepted) invite for this email
    const { data: existing } = await sb
      .from('member_invites')
      .select('id, accepted_at, token_expires_at')
      .eq('society_id', SOCIETY_ID)
      .eq('email', email)
      .is('accepted_at', null)
      .gt('token_expires_at', new Date().toISOString())
      .maybeSingle();

    if (existing) {
      return Response.json(
        { error: 'CONFLICT', message: 'A pending invite already exists for this email address' },
        { status: 409 },
      );
    }

    // token_expires_at = NOW() + expiryDays days
    const tokenExpiresAt = new Date(Date.now() + expiryDays * 24 * 60 * 60 * 1000).toISOString();

    const { data, error } = await sb
      .from('member_invites')
      .insert({
        society_id: SOCIETY_ID,
        email,
        flat_number: body.flat_number.trim(),
        intended_role: intendedRole,
        committee_title: body.committee_title?.trim() ?? null,
        invited_by: user.id,
        token_expires_at: tokenExpiresAt,
      })
      .select('id, email, token_expires_at')
      .single();

    if (error) throw Object.assign(new Error(error.message), { status: 500 });

    return Response.json(data, { status: 201 });
  } catch (err) {
    return normalizeError(err, request.url);
  }
};
